/*
 * File: ReportGenerator.java
 */
package utils;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.util.Date;
import java.util.concurrent.ThreadLocalRandom;

/**
 * This class handles the generation of a score report. A complete score report contains
 * the following information:
 * <br><br>1. The session ID (aka report ID)
 * <br>2. The score and respective percentage
 * <br>3. The number of questions incorrectly answered 
 * <br>4. Which questions were answered incorrectly (identifed by their numbers)
 * <br>5. The time taken to complete the quiz
 * <br><br>Naturally, a report will be different between multiple sessions. 
 * @author Ahmed Ghannam
 *
 */
public class ReportGenerator {
	private static int reportId = ThreadLocalRandom.current().nextInt(1, 1000 + 1);;
	private static boolean hasGeneratedReport = false; 
	
	/**
	 * Constructs and returns a new report for the current quiz session, given the results.  
	 * @param result the results of this session
	 * @return the constructed report for this session 
	 */
	private static String constructReport(Result result) {
		StringBuilder report = new StringBuilder();
		Date date = new Date();
		report.append("\t\t\t************************************")
				.append("\n\t\t\tASTRONOMY QUIZ AUTO-GENERATED REPORT")
				.append("\n\t\t\t************************************")
				.append("\n\n- Session ID: ".concat(String.valueOf(reportId))).append("\n- Total score: ")
				.append(String.valueOf(result.getScore()).concat(" / 15")).append("\n- Total score percentage: ")
				.append(String.valueOf(result.getPercentage()).concat("%"))
				.append("\n- Number of questions answered incorrectly: ")
				.append(String.valueOf(result.getIncorrectAnswerCount()))
				.append("\n- Question(s) answered incorrectly: ")
				.append(String.valueOf(result.getIncorrectlyAnswered()))
				.append("\n- Total time taken to complete quiz: ")
				.append(String.valueOf(result.getElapsedTime()).concat(" minutes"))
				.append("\n\n*** This report was autogenerated by Astronomy Quiz on ").append(date.toString())
				.append(".***");
		return report.toString();
	}
	
	/**
	 * Writes the report to an external file, which is then delegated to <code>generate()</code>. 
	 * @throws Exception if an IO error occurs
	 */
	private static void toFile() throws Exception {
		File desktop = new File(System.getProperty("user.home"), "/Desktop"); 
		String fileName = "score_report_".concat(String.valueOf(reportId)).concat(".txt");
		File fullPath = new File(desktop, fileName); 
		String data = constructReport(new Result());
		try (Writer writer = new BufferedWriter(new OutputStreamWriter(new 
				FileOutputStream(fullPath), "utf-8"))) {
			writer.write(data);
		} 
		hasGeneratedReport = true; 
		updateId();
	}
	
	/**
	 * Generates a text file containing the report for this quiz session, which is saved 
	 * to the user's desktop. 
	 */
	public static void generate() {
		try {
			toFile();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	/**
	 * Updates the current report ID with a new, randomly generated value. 
	 */
	private static void updateId() {
		reportId = ThreadLocalRandom.current().nextInt(1, 1000 + 1);
	}
	
	/**
	 * Checks if a report has already been generated for the current session. 
	 * @return <code>true</code> if a report has already been generated, <
	 * code>false</code> otherwise
	 */
	public static boolean hasGeneratedReport() {
		return hasGeneratedReport == true; 
	}
	
	/**
	 * Resets the generator for the current session. 
	 */
	public static void reset() {
		hasGeneratedReport = false; 
	}
}
